runtimeverification/michelson-semantics

- tests/unit/car_00.tzt
- tests/unit/car_01.tzt
- tests/unit/cdr_00.tzt
- tests/unit/cdr_01.tzt
- tests/unit/ediv_int-int_00.tzt
- tests/unit/ediv_int-int_01.tzt
- tests/unit/ediv_int-int_02.tzt
- tests/unit/ediv_int-int_03.tzt
- tests/unit/ifnone_optionnat_00.tzt
- tests/unit/size_mapintint_00.tzt
- tests/unit/unpair_pairstringstring_00.tzt
A few straightforward fixes to the unit tests.
> Fix types and arity in unit tests

- Dockerfile
- Jenkinsfile
- build-deps.sh
Update the build scripts so that Jenkins builds the tool with crypto hooks integrated.
> Jenkins Update

- Jenkinsfile
- tests/unit/createcontract_00.tzt
Jenkin will now call the `./run-tests.sh` script.
> Run tests on each commit with Jenkins

- Dockerfile
- Jenkinsfile
- README.md
- _config.yml
- michelson-config.md
- michelson-internal-syntax.md
- michelson-syntax.md
- ssh/config
Jenkins should now generate a website for each commit of our project.
> Make Jenkins generate a website from our literate code

- Jenkinsfile
This is entirely cosmetic and shouldn't affect anything --- it just add an air of professionalism.
> Make dir step in Jenkinsfile project generic

- Makefile
- README.md
- compat.md
- lib/tezos-client-unit-test
- michelson/common.md
- michelson/configuration.md
- michelson/michelson.md
- michelson/syntax.md
- symbolic/configuration.md
- symbolic/symbolic.md
- unit-test/unit-test.md
> Simplify semantics initialization

- Makefile
- michelson.md
- syntax.md
- tests/failing.unit
- tests/multi/simple_00.tzt
- tests/multi/simple_01.tzt
- tests/multi/simple_02.tzt
- tests/multi/simple_03.fail.tzt
Fixes: runtimeverification/firefly-michelson#6
> Add multitest format

- Makefile
- tests/failing.prove
- tests/proofs/multisig-spec.md
Fixes: runtimeverification/firefly-michelson#21
> Document multisig proof

- syntax.md
Fixes: runtimeverification/firefly-michelson#22
> syntax: simplify instruction syntax

- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
> dexter: add proof base for set_baker entrypoints

- tests/proofs/return-spec.k
I moved this to it's on PR since it has nothing to do with the `set-manager-spec`. Thanks for finding it!
> proofs/return-spec: Fix warnings: rule => claim

- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
> Add <operations> cell

- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
> Add proof for set_lqt_address entrypoint

- Jenkinsfile
- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
> Add default entrypoint spec

- tests/proofs/dexter/dexter-compiled.md
- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
Closes #206 
I have a working positive case for the `update_token_pool` function but I have some question marks. I'm not sure exactly why some of these initial values need to look the way they look, or if the way I've written the spec is sound. Help appreciated.
> Update token pool spec

- tests/proofs/dexter/dexter-compiled.md
- tests/proofs/dexter/dexter.md
This PR provides improvements which are used by three in-progress PRs: #250, #251, and #252.
Currently, I have rebased the three PRs above on top of this branch.
> Dexter Proof Simplifications

- Makefile
- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
The trivial cases for remove liquidity
> Remove liq negative

- Dockerfile
- Jenkinsfile
- Makefile
- michelson.md
- tests/proofs/dexter/dexter-compiled.md
- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
Currently only has the negative case.
> Add liquidity spec negative case

- Makefile
- common.md
- compat.md
- michelson.md
- syntax.md
- tests/failing.cross
- tests/proofs/dexter/dexter-compiled.md
- tests/proofs/dexter/dexter-spec.md
- tests/proofs/dexter/dexter.md
- tests/proofs/multisig-spec.md
- tests/proofs/return-spec.k
- tests/proofs/sum-to-n-spec.k
- tests/unit/contract_06.tzt
- tests/unit/contract_07.tzt
- tests/unit/contract_08.tzt
- tests/unit/self_01.tzt
- tests/unit/self_02.tzt
- tests/unit/self_03.tzt
If this is merged after #226, we need to update the update token pool spec to correct how entrypoints are handled.
Fixes: #231
> Add semantics of entrypoints

- Jenkinsfile
- Makefile
- tests/proofs/liquidity-baking/lb-spec.md
- tests/proofs/liquidity-baking/lb.md
@nishantjr Feel free to review but please do not merge yet because there is a minor issue with the git commit history I'd like to resolve. Thanks.
Fixes: #296
> Add Liquidity Baking `tokenToXtz` spec

- Makefile
- tests/proofs/liquidity-baking/lb-spec.md
> Add Liquidity Baking `xtzToToken` spec

- Makefile
- tests/proofs/liquidity-baking/lb-spec.md
This should be merged after #316
Fixes: #300
> Add Liquidity Baking `default` spec

- common.md
- michelson.md
- syntax.md
- tests/failing.cross
- tests/unit/join_tickets_00.tzt
- tests/unit/join_tickets_01.tzt
- tests/unit/join_tickets_02.tzt
- tests/unit/read_ticket_00.tzt
- tests/unit/split_ticket_00.tzt
- tests/unit/split_ticket_01.tzt
- tests/unit/ticket_00.tzt
> WIP: Semantics of tickets
