runtimeverification/michelson-semantics

build.sh
compat/michelson-unparser.k
michelson-common.k
michelson-config.k
michelson-syntax.k
michelson.k
parser.sh
run.sh

We no longer invoke the java frontend unless the test fails, which substantially improves performance. In order to do this, we generate a parser with Bison rather than relying on the java `kast` parser to parse programs. We also transform the semantics slightly to account for the limitations of this approach, like lack of support for macros and a lack of support for non-LALR(1) grammars.

Performance optimization

---

michelson.md
tests/unit/packunpack_address_00.tzt
tests/unit/packunpack_bool_00.tzt
tests/unit/packunpack_bytes_00.tzt
tests/unit/packunpack_int_00.tzt
tests/unit/packunpack_keyhash_00.tzt
tests/unit/packunpack_mutez_00.tzt
tests/unit/packunpack_nat_00.tzt
tests/unit/packunpack_string_00.tzt
tests/unit/packunpack_timestamp_00.tzt

`UNPACK type` has return type `option type` which our semantics doesn't correctly capture --- bug was found by running cross-validation tests.
Marked as draft because this will be an easy merge after we merge in other more important stuff.

fix unpack semantics and update unit tests

---

Dockerfile
Jenkinsfile
build-deps-k.sh
build-deps-tezos.sh

~Not ready for merge.~
@sskeirik and @Andrew-Miranti this is ready for review now. It makes it so that we use the K dockerhub image on CI, which cuts out the K building steps from every CI run.
I would recommend making a follow-up PR which also tries to install as many of the ocaml dependencies as possible in the Dockerfile, to maximize cacheing and speed up the tezos dependency step. But this should get in first.

Use K DockerHub images on CI

---

README.md
tests/README.md

Since `build-deps.sh` automatically grabs the git submodules and runs the relevant build commands for K and Tezos, we can simplify the documentation.
I also documented the dependencies that we use.

update docs to clarify dependencies and build instructions

---

Jenkinsfile

Add `-r` to rm so that we remove submodule directories which get listed by `git ls-files`.
Reorder the file deletion commands so that every file listed by `git ls-files` exists --- obviating the need for a `-f`.

fix web deployment

---

Jenkinsfile

I accidentally deleted the `_config.yml` file in the Jenkinsfile web deploy which defines the website theme. Update the grep regex to ignore this file. Also, ensure that the dot `.` is a literal dot and not a catchall.

fix Jenkinsfile web deploy

---

Jenkinsfile

Last command accidentally dropped `-r` flag. We reintroduce it.

Fix rm command in Jenkins web deploy

---

Jenkinsfile
Makefile
fix-address.sh
kmich
run-tezos.sh
run-with-tezos.sh

This is blocked on #39 . It:
-   Generates the bison parser when kompiling the definitions.
-   Fixes some typos throughout the `kmich` script.
-   Adds a command `interpret` to the `kmich` script which uses the generated bison parser and the fast LLVM backend unparser when running programs.
-   Switches the `Makefile` to use `interpret` instead of `run` for a massive speedup in running tests.

Re-enable Bison parser and fast unparser

---

lib/michelson-test-check

This commit prints more cells for bad states: k, stack, and symbols as well as all constraints.
The set of cells printed is also easily configurable (see line 49).

Improve symbolic test result printer

---

Makefile
compat.md
michelson-unparser.md
michelson/common.md
michelson/michelson.md
michelson/syntax.md
michelson/types.md
tests/failing.unit
unit-test/unit-test.md

Commit 'michelson/common.md: address unused variable warnings' appears to be last good commit.
Building with the last commit causes compilation errors (bison) when building the core semantics.
It seems like some unused symbol is accidentally getting imported into the main semantics but I cannot figure out which one.

Fix unused symbol/variable warnings

---

Makefile
common.md
michelson.md

As I understand, the builtin list can cause problems with theorem proving, so we use a custom list implementation.

Reimplement Michelson `list`s using `InternalList`

---

michelson.md

Note: some rule side-conditions still use the less than integer comparisons because that seems slightly more readable.
However, I'm not sure if this will cause problems for symbolic reasoning down the road.

Better normalize abstract terms for symbolic reasoning

---

kmich
michelson.md
syntax.md
tests/lib/abs.tzt
tests/multi/include_00.tzt
tests/multi/include_01.tzt
tests/multi/include_02.tzt
tests/multi/include_03.tzt

Currently, relative paths are interpreted relative to `./kmich` and not to the file which we are importing from.
This is not ideal, but I'm not sure of the best way to fix this.
My thought is we can merge this now and come back and fix this issue later. Thoughts?
Fixes: runtimeverification/firefly-michelson#16

michelson: add file inclusion functionality

---

tests/proofs/dexter/dexter.md

This PR implements:
- Two functions relating to produce Michelson types (needed to produce a well-formed Michelson stack cell, which includes a type tag):
- a function `#DexterParamType` which builds the contract parameter type in Michelson corresponding to the Dexter contract parameter type (in both the FA12 and FA2 versions)
- a function `#DexterStorageType` which builds the contract storage type in Michelson corresponding to the Dexter contract storage type (in both the FA12 and FA2 versions)
- a conversion function from our abstract storage value + abstract parameter value into an initial Michelson stack input corresponding to the Dexter contract input (in both the FA12 and FA2 versions)
- a conversion function from the final Michelson stack cell data into the Dexter contract abstract …

Implement abstract state serialization

---

tests/proofs/dexter/dexter-compiled.md
tests/proofs/dexter/dexter-spec.md

- Annotating the Dexter code with Left/Right entry points.
- A function for choosing between the two code macros, so we can write a single spec for both versions in the cases where the version doesn't matter.
```
claim <k> #dexterCode(IsFA2) => . ... </k>
<storage> [...] </storage>
```

Nice to haves

---

Makefile
tests/proofs/dexter/dexter-spec.md
tests/proofs/dexter/dexter.md

Note: currently this PR only includes the positive case. The negative case is still pending.
All of the main assumptions should be present for the positive case to go through (assuming backend support). The main trick will be adding additional uninterpreted functions to prevent the backend from crashing with `DecidePredicateUnknown`.
Fixes: #249

Add `token_to_token` spec

---

kmich
lib/kast-lb.kscript
tests/proofs/dexter/dexter-spec.md
tests/proofs/dexter/dexter.md
tests/proofs/liquidity-baking/lb-compiled.md
tests/proofs/liquidity-baking/lb-spec.md
tests/proofs/liquidity-baking/lb.md

Updates include:
- fix entrypoint syntax
- add `#XtzBurn` macro for representing burn fee calculations
- add missing burn txns for conversion entrypoints
- add kast script for lb specs and `kmich` support
- mark unused variables to quiet warnings
EDIT: In my history, this is on top of #308, but technically, they don't depend on each other at all, so this could be merged first, if that would be more helpful. I am hopeful that, after this latest round of fixes, the updated Dexter specs should pass.

Miscellaneous updates to liquidity baking spec

---

Dockerfile
Makefile
common.md
compat.md
lib/combine.py
michelson.md
pretty-syntax.md
syntax.md
tests/failing.cross
tests/proofs/dexter/dexter-spec.md
tests/proofs/dexter/dexter.md
tests/proofs/liquidity-baking/lb-spec.md
tests/proofs/lqt/lqt-spec.md
tests/proofs/multisig-spec.md
tests/proofs/return-spec.k
tests/unit/push_pair_00.tzt
tests/unit/push_pair_01.tzt
tests/unit/push_pair_02.tzt
tests/unit/push_pair_03.tzt
tests/unit/push_pair_04.tzt

This PR updates the Tezos submodule from v7 to v10 and also fixes some build issues that I had on OSX.
- build: fix build command parsing on OSX by removing some spaces/adding extra quotes
- build: simplfy kompile invocation: only set needed options
- build: install rustup in CI container for later tezos
- tezos: bump from v7 to v10 (current version, but will probably be upgraded soon)
- expand parser to support new pair syntax (required for cross compatibility test harness support)
- update internal list syntax to avoid ambiguity due to new pair syntax
- add tests for new pair syntax
- fix cross test harness to support new pair syntax
- disable 2 tests that do not seem to be compatible with tezos v10
- update proof tests to use new internal list notation
**NOTE:** We probably do not …

Update Tezos to v10

---

michelson.md

Fix a typo: structrual -> structural

---

Dockerfile
INSTALL.md

This PR reflects a pending change in the upstream K distribution; it updates package files and documentation to reflect the new version of Z3 we require.

Bump Z3 version to 4.8.15

---

kmich

This PR switches `kwasm prove` over to `kprove-legacy`, in preparation for `kprovex` being renamed.

Deprecate old `kprove` tool
